Question 1 cleaning the data set

In [99]:
import pandas as pd
import numpy as np

In [100]:
data=pd.read_csv('data.csv')
data.drop_duplicates(inplace=True)


REMOVING COLUMN WHICH WAS USELESS AND  ALMOST HAD SAME VALUE

In [101]:
data.drop(['Photo','Flag','Club Logo','Real Face'],axis=1,inplace=True)


In [102]:
x=data.iloc[0:,:-1].values
print(x[:,28:50])

[['93+2' '93+2' '93+2' ... '47+2' '47+2' '59+2']
 ['90+3' '90+3' '90+3' ... '53+3' '53+3' '61+3']
 ['89+3' '89+3' '89+3' ... '47+3' '47+3' '60+3']
 ...
 ['46+2' '46+2' '46+2' ... '28+2' '28+2' '33+2']
 ['46+2' '46+2' '46+2' ... '31+2' '31+2' '35+2']
 ['44+2' '44+2' '44+2' ... '47+2' '47+2' '46+2']]


In [108]:
import numpy as np

# Define a function to evaluate expressions and return the result as an integer
def evaluate_expression(expr):
    try:
        if isinstance(expr, str):
            # Use the eval function to evaluate the expression and convert it to an integer
            result = int(eval(expr))
            return result
        else:
            return None
    except (SyntaxError, ZeroDivisionError, NameError, ValueError):
        # Handle potential errors in the expressions
        return None

# Assuming you have already converted the specified columns to strings
# Create a copy of the specified columns to store the evaluated results
evaluated_values = np.empty(x[:, 28:50].shape, dtype=np.float64)

# Apply the evaluation function to the specified columns
for i in range(evaluated_values.shape[0]):
    for j in range(evaluated_values.shape[1]):
        evaluated_values[i, j] = evaluate_expression(x[i, 28 + j])

# Print the NumPy array with the evaluated results for the specified columns
print(evaluated_values)

x[:,28:50]=evaluated_values

[[95. 95. 95. ... 49. 49. 61.]
 [93. 93. 93. ... 56. 56. 64.]
 [92. 92. 92. ... 50. 50. 63.]
 ...
 [48. 48. 48. ... 30. 30. 35.]
 [48. 48. 48. ... 33. 33. 37.]
 [46. 46. 46. ... 49. 49. 48.]]


Replacing missing values

In [109]:
from sklearn.impute import SimpleImputer

#Here we are using mean method to replace the missing value we can also use most_frequent or median or some standard valued that we would like
imputer =SimpleImputer(missing_values=np.nan,strategy="mean")
x[:,28:50]=imputer.fit_transform(x[:,28:50])
print(x[:,28:50])

[[95.0 95.0 95.0 ... 49.0 49.0 61.0]
 [93.0 93.0 93.0 ... 56.0 56.0 64.0]
 [92.0 92.0 92.0 ... 50.0 50.0 63.0]
 ...
 [48.0 48.0 48.0 ... 30.0 30.0 35.0]
 [48.0 48.0 48.0 ... 33.0 33.0 37.0]
 [46.0 46.0 46.0 ... 49.0 49.0 48.0]]
